version: '3.9'
services:
  react-webapp:
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    volumes:
      - './react:/app'
      - '/app/node_modules'
    ports:
      - 7000:3000
    env_file:
      - ./react/.env
  wikijs-pgdb:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - ./wikijs/db-data:/var/lib/postgresql/data
    ports:
      - 7002:5432
  wikijs:
    image: requarks/wiki:latest
    depends_on:
      - wikijs-pgdb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-pgdb
      DB_PORT: 5432
      DB_NAME: wikijs
      DB_USER: wikijs
      DB_PASS: wikijs
    restart: unless-stopped
    ports:
      - 7001:3000

volumes:
  db-data: