# pull official base image
FROM node:16.13-buster as build-stage

# set working directory
WORKDIR /app

# install app dependencies
COPY package*.json ./
RUN npm install --silent

# Build app
COPY . .
RUN npm run build --silent

# production environment
FROM nginx as prod
COPY --from=build-stage /app/build /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=build-stage /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf