# pull official base image
FROM node:16.13-buster as dev

# set working directory
WORKDIR /app

# install app dependencies
COPY package*.json ./

# Build app
COPY . .
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]